// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/okontajneroch/starwars/clientset/typed/starwars/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeStarwarsV1 struct {
	*testing.Fake
}

func (c *FakeStarwarsV1) Starfighters(namespace string) v1.StarfighterInterface {
	return newFakeStarfighters(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeStarwarsV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
